### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by d-cameron** [10XGenomics/rust-debruijn#20]
I'm new to rust and I have some API clarfications that I am unsure if it's a missing feature in this library, or something I've overlooked. Clarification or examples on the following points would be greatly appreciated:

- is there an efficient way to calculate hamming distance on DnaStringSlice?

`hamming_distance()` requires a `DnaString` which means I need to convert to `Vec<u8>` then `DnaString` to perform what could be an only slightly more expensive operation than the current `hamming_distance` implementation.

- How do I iterate over the kmers in a DnaStringSlice/DnaString?

I feel like I'm missing something really obvious here. I'm trying to do something like `Kmer16::string_iter(&slice)` but can't seem to find the right function or an example of this in the docs.

- Is there a way to efficiently load a `DnaString` from a `rust-htslib` `Seq` object?

htslib uses a 4bit encoding and it seems the only approach is to decode back to the raw 8-bit u8 encoding then back 2bit format.

Thanks

**Comment by d-cameron** [comment]
`dnaslice.iter_kmers::<Kmer16>();`

Would a PR with additional documentation be useful?

**Comment by pmarks** [comment]
Hi @d-cameron, these are great questions.  PR's to improve the docs would be much appreciated. An example of how to iterate over kmers as you're showing would be great! `iter_kmers` is defined on the `Vmer` trait, so that needs to be in scope.

We don't have a `hamming_distance` impl for `DnaStringSlice` - I'll try to add that soon.

 >Is there a way to efficiently load a DnaString from a rust-htslib Seq object?
 A loop that converts the iterates over bases from `Seq` and `push`es the bytes onto a `DnaString` will be pretty fast.  You want to avoid creating an intermediate `Vec<u8>` A custom SIMD-ified method could in theory be ~8x faster but is a bit of a project.
